### ISSUE TITLE
Flawed text wrapping algorithm 

### ISSUE THREAD

**Issue by nbransby** [LemonCake/MSLabel#1]
If all you want is a label with the ability to change the line spacing there is very little to choose from on github. The example you mentioned, MTLabel, says there's a known issue in drawing in table cell due to the fact he uses performSelector:withObject:afterDelay:. Any code using this method instantly rings alarm bells in my head. 

Anyway your solution seemed ideally as although it only supports one lineBreakMode it was the one I needed but alias your text wrapping code gets stuck in an infinite loop and after inspection I can see if needs some serious optimisation.

Hope you get the time to fix it as this is useful little class

**Comment by LemonCake** [comment]
Hey thanks. I know exactly where the infinite loop occurs (embarrassing). I actually made a fix a while ago but haven't pushed it yet. I'll introduce a fix sometime today.

**Comment by LemonCake** [comment]
There just pushed. The infinite loop happens if the first word on the line is too wide for the label. In that case I just let it overflow anyway. It shouldn't be too hard to support the other linebreakmodes. Code contributions are welcome. :)
