### ISSUE TITLE
Calling sizeToFit cuts off lines of text

### ISSUE THREAD

**Issue by joshuafeldman** [LemonCake/MSLabel#3]
Nice subclass. Calling sizeToFit though produces unexpected results.

**Comment by LemonCake** [comment]
Yea, dont' think sizeToFit will work very well. This was a pretty shoddy job for a very specific purpose. :P

**Comment by joshuafeldman** [comment]
Had a feeling is was a one implementation sort of thing. Cool idea though, it could be taken pretty far if you wanted.

Nice job.
