### ISSUE TITLE
Vertical alignement ?

### ISSUE THREAD

**Issue by thomasjoulin** [LemonCake/MSLabel#4]
I'm trying to figure out how to bring back the middle vertical alignement from the standard UILabel. Any idea how to start ?

Thanks,

**Comment by LemonCake** [comment]
Do you mean center alignment?

**Comment by thomasjoulin** [comment]
Yes, the center vertical alignement, which is the default and only option for standard UILabel. Your code seems to align at the top. For example a UILabel with large height and a blue background :

![UILabel](http://i.imgur.com/oVeUq.png)

**Comment by LemonCake** [comment]
hmm shouldn't be too hard to do actually. You know how many lines there are ahead of time and the line height they will assume prior to drawing. So you just have to calculate the distance from the top to start drawing. In this case:

(int)(( label.height - (lines.count \* lineheight) ) / 2 ) = y coordinate from which you start drawing

For left/right centering for each line you can do something simliar to calculate where to start with drawing the line on the x axis.

Hope that helps. :)

**Comment by thomasjoulin** [comment]
Fixed by [pull request #10](https://github.com/LemonCake/MSLabel/pull/10)

**Comment by LemonCake** [comment]
I'll review and merge this in. Thanks!
